title: Isomer Guide
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-isomer-guide
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  #----> Optional, Google analytics ID

fast_build: false
offline: false
preload_pages: true

styling_options:
  primary_brand_color: '#444'  #----> Optional, theme color
  logo_path: /assets/logo.png  #----> Optional, path to logo
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df #----> Optional, feedback url

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/'
    title: 'Isomer Guide'
    subtitle: ''
    order:
      - 'sample.md'